x-common-settings: &enable-cuda-jetson
  environment:
    - NVIDIA_VISIBLE_DEVICES=all
  runtime: nvidia
  shm_size: '1gb'

services:
  project:
    <<: *enable-cuda-jetson
    build: project
    volumes: 
      - ./project:/app
